name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

permissions:
  contents: read

jobs:
  regression-tests:
    name: All regression tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: adafruit/Adafruit_GPS
        ref: 1.9.0
        path: gps-dependency
    - name: Run all tests with sanitizers
      run: python3 extras/tests/run_tests.py --gps-dir gps-dependency

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v4
      with:
        repository: adafruit/ci-arduino
        path: ci
    - uses: actions/checkout@v4
      with:
        repository: adafruit/Adafruit_GPS
        ref: 1.9.0
        path: gps-dependency
    - name: Install prerequisites
      run: bash ci/actions_install.sh
    - name: Install released GPS dependency
      run: cp -R gps-dependency "$HOME/Arduino/libraries/Adafruit_GPS"
    - name: Build examples
      run: python3 ci/build_platform.py main_platforms feather_esp32s3
    - name: Check formatting
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -e "gps-dependency/*" -r .
    - name: Generate documentation
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN || github.token }}
        PRETTYNAME: "Adafruit LC29H Arduino Library"
      run: bash ci/doxy_gen_and_deploy.sh src
